# Generated by Django 3.1.3 on 2021-10-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='lesson',
        ),
    ]
