# Generated by Django 3.1.3 on 2022-02-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20220216_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(),
        ),
    ]
