# Generated by Django 3.1.3 on 2022-04-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20220216_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='total_learners',
        ),
    ]
